application: nimobileapps
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: .*
  script: main.py
  secure: always

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe